- name: 开机自动启动
  lineinfile: 
    path: /etc/rc.local
    line: "export JAVA_HOME=/usr/local/jdk && export PATH=$JAVA_HOME:/bin:$PATH && cd {{ app_dir }} && ./bin/kafka-server-start.sh -daemon config/server.properties"

- name: rc.local添加x权限
  file:
    path: /etc/rc.d/rc.local
    mode: +x
