version: 2
jobs:
  build:
    docker:
      - image: docker:18.09.3-git
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - checkout
      - run : |
          export COMMIT_SHA=$(git log -1 --pretty=format:"%H" | awk '{print substr($1,1,8)}') 
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
          docker build --build-arg COMMIT_SHA=${COMMIT_SHA} -t setzero/kubeadm-ha:${CIRCLE_BRANCH}-${COMMIT_SHA} .
          docker push setzero/kubeadm-ha:${CIRCLE_BRANCH}-${COMMIT_SHA}
workflows:
  version: 2
  build:
    jobs:
    - build