version: "3"
services:
  mysql:
    image: mysql:5.7.27 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      TZ: Asia/Shanghai
    volumes:
      - /data/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /data/mysql/data:/var/lib/mysql
