- name: 获取ansible_kernel
  setup:
    filter: ansible_kernel

- name: 加载内核模块
  modprobe: 
    name: "{{ item }}"
    state: present
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_sh
  - ip_vs_wrr
  - br_netfilter
  ignore_errors: true

- name: 加载nf_conntrack for kernel < 4.19
  modprobe: 
    name: nf_conntrack_ipv4
    state: present
  when: ansible_kernel is version('4.19', '<')
  ignore_errors: true

- name: 加载nf_conntrack for kernel >= 4.19
  modprobe: 
    name: nf_conntrack
    state: present
  when: ansible_kernel is version('4.19', '>=')
  ignore_errors: true

- name: 设置 systemd-modules-load 配置
  template: 
    src: k8s-ipvs-modules.conf.j2
    dest: /etc/modules-load.d/k8s-ipvs-modules.conf

- name: 启动/重启 systemd-modules-load
  service:
    name: systemd-modules-load
    state: restarted
    enabled: yes
